// =============================================================================
// BitFlow - PostgreSQL Relational Schema Definitions (14 Tables)
// Type-safe schema definitions, relationships, and table metadata
// =============================================================================

export interface TableColumnMetadata {
  name: string;
  type: string;
  isPrimary?: boolean;
  isNullable?: boolean;
  isUnique?: boolean;
  references?: { table: string; column: string; onDelete?: string };
  defaultValue?: string;
  description: string;
}

export interface TableDefinition {
  name: string;
  category: "Identity & RBAC" | "Entities & Accounts" | "Ledger & Blockchain" | "Detection & Intelligence" | "SOC Operations" | "Audit & System";
  description: string;
  primaryKey: string;
  columns: TableColumnMetadata[];
  indexes: string[];
}

export const POSTGRESQL_TABLES_METADATA: Record<string, TableDefinition> = {
  users: {
    name: "users",
    category: "Identity & RBAC",
    description: "Core platform credentials, identity, and role-based access control (ADMIN, ANALYST, VIEWER)",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "System UUID identifier" },
      { name: "email", type: "VARCHAR(255)", isUnique: true, description: "Analyst email address" },
      { name: "username", type: "VARCHAR(100)", isUnique: true, description: "Unique SOC username handle" },
      { name: "hashed_password", type: "VARCHAR(255)", description: "Bcrypt password hash" },
      { name: "full_name", type: "VARCHAR(255)", description: "Official personnel display name" },
      { name: "avatar_url", type: "VARCHAR(512)", isNullable: true, description: "Profile photo URL" },
      { name: "role", type: "VARCHAR(50)", defaultValue: "'ANALYST'", description: "RBAC tier: ADMIN | ANALYST | VIEWER" },
      { name: "is_active", type: "BOOLEAN", defaultValue: "TRUE", description: "Account enabled status" },
      { name: "is_verified", type: "BOOLEAN", defaultValue: "FALSE", description: "MFA verification status" },
      { name: "is_superuser", type: "BOOLEAN", defaultValue: "FALSE", description: "Superuser elevation flag" },
      { name: "last_login_at", type: "TIMESTAMP WITH TIME ZONE", isNullable: true, description: "Last session authentication timestamp" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Creation audit timestamp" },
      { name: "updated_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Last modification timestamp" },
    ],
    indexes: ["idx_users_email", "idx_users_username", "idx_users_role", "idx_users_is_active"],
  },

  members: {
    name: "members",
    category: "Entities & Accounts",
    description: "100 Synthetic KYC demo profiles, identity verification, and nominee details (M001-M100)",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "member_id", type: "VARCHAR(32)", isUnique: true, description: "Synthetic member code (M001-M100)" },
      { name: "user_id", type: "UUID", isNullable: true, references: { table: "users", column: "id", onDelete: "SET NULL" }, description: "Linked platform user" },
      { name: "name", type: "VARCHAR(255)", description: "Synthetic individual full name" },
      { name: "email", type: "VARCHAR(255)", description: "Demo contact email" },
      { name: "phone", type: "VARCHAR(64)", description: "Demo telephone number" },
      { name: "age", type: "INTEGER", isNullable: true, description: "Age in years" },
      { name: "gender", type: "VARCHAR(20)", isNullable: true, description: "Gender identity" },
      { name: "city", type: "VARCHAR(100)", isNullable: true, description: "Residential city" },
      { name: "state", type: "VARCHAR(100)", isNullable: true, description: "Residential state" },
      { name: "country", type: "VARCHAR(100)", defaultValue: "'India'", description: "Country of residence" },
      { name: "occupation", type: "VARCHAR(100)", isNullable: true, description: "Professional occupation" },
      { name: "annual_income_inr", type: "NUMERIC(18, 2)", isNullable: true, description: "Annual income in INR" },
      { name: "profile_status", type: "VARCHAR(50)", defaultValue: "'Active'", description: "Profile standing: Active | Review | Suspended" },
      { name: "kyc_status", type: "VARCHAR(50)", defaultValue: "'Verified'", description: "AML KYC state: Verified | Pending | Flagged" },
      { name: "synthetic_id_ref", type: "VARCHAR(128)", isNullable: true, description: "Masked synthetic identity reference" },
      { name: "nominee_name", type: "VARCHAR(255)", isNullable: true, description: "Beneficiary nominee name" },
      { name: "nominee_relation", type: "VARCHAR(100)", isNullable: true, description: "Relationship with nominee" },
      { name: "risk_rating", type: "VARCHAR(50)", defaultValue: "'Low'", description: "Entity baseline risk rating" },
      { name: "metadata", type: "JSONB", defaultValue: "'{}'::jsonb", description: "Extensible demographic metadata" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Record creation timestamp" },
      { name: "updated_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Record update timestamp" },
    ],
    indexes: ["idx_members_member_id", "idx_members_name", "idx_members_email", "idx_members_profile_status", "idx_members_kyc_status", "idx_members_risk_rating"],
  },

  accounts: {
    name: "accounts",
    category: "Entities & Accounts",
    description: "Financial bank custody and fiat settlement accounts associated with members",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "account_number", type: "VARCHAR(64)", isUnique: true, description: "Synthetic bank account ID (DEMO-BANK-000001)" },
      { name: "member_id", type: "UUID", references: { table: "members", column: "id", onDelete: "CASCADE" }, description: "Foreign key to member entity" },
      { name: "bank_name", type: "VARCHAR(100)", defaultValue: "'BitFlow Treasury Bank'", description: "Financial institution name" },
      { name: "account_type", type: "VARCHAR(50)", defaultValue: "'Savings'", description: "Savings | Current | Escrow | Custody" },
      { name: "ifsc_code", type: "VARCHAR(32)", defaultValue: "'BITF0001928'", description: "IFSC routing code" },
      { name: "branch", type: "VARCHAR(100)", defaultValue: "'Main FinTech Hub'", description: "Branch jurisdiction" },
      { name: "balance_fiat", type: "NUMERIC(18, 2)", defaultValue: "0.00", description: "Current fiat balance" },
      { name: "currency", type: "VARCHAR(10)", defaultValue: "'INR'", description: "Fiat denomination (INR, USD)" },
      { name: "status", type: "VARCHAR(50)", defaultValue: "'Active'", description: "Account state: Active | Frozen | Closed" },
      { name: "daily_limit_fiat", type: "NUMERIC(18, 2)", defaultValue: "1000000.00", description: "Daily maximum fiat clearance" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Opening timestamp" },
      { name: "updated_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Last change timestamp" },
    ],
    indexes: ["idx_accounts_account_number", "idx_accounts_member_id", "idx_accounts_status"],
  },

  wallets: {
    name: "wallets",
    category: "Entities & Accounts",
    description: "Cryptocurrency Bitcoin on-chain addresses, balances, and custody tiers",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "address", type: "VARCHAR(128)", isUnique: true, description: "Bitcoin bech32/native SegWit or Taproot address" },
      { name: "member_id", type: "UUID", references: { table: "members", column: "id", onDelete: "CASCADE" }, description: "Owning synthetic member" },
      { name: "account_id", type: "UUID", isNullable: true, references: { table: "accounts", column: "id", onDelete: "SET NULL" }, description: "Linked settlement account" },
      { name: "label", type: "VARCHAR(100)", isNullable: true, description: "Analyst or customer assigned label" },
      { name: "wallet_type", type: "VARCHAR(50)", defaultValue: "'SegWit (Native)'", description: "Address format and derivation model" },
      { name: "balance_btc", type: "NUMERIC(18, 8)", defaultValue: "0.00000000", description: "Confirmed on-chain BTC balance" },
      { name: "unconfirmed_btc", type: "NUMERIC(18, 8)", defaultValue: "0.00000000", description: "Pending unconfirmed balance" },
      { name: "total_received_btc", type: "NUMERIC(18, 8)", defaultValue: "0.00000000", description: "Lifetime incoming volume" },
      { name: "total_sent_btc", type: "NUMERIC(18, 8)", defaultValue: "0.00000000", description: "Lifetime outgoing volume" },
      { name: "tx_count", type: "INTEGER", defaultValue: "0", description: "Total processed transaction count" },
      { name: "derivation_path", type: "VARCHAR(100)", defaultValue: "'m/84\'/0\'/0\'/0/0'", description: "BIP-44/84 key derivation path" },
      { name: "is_active", type: "BOOLEAN", defaultValue: "TRUE", description: "Active monitoring indicator" },
      { name: "is_flagged", type: "BOOLEAN", defaultValue: "FALSE", description: "High risk surveillance flag" },
      { name: "last_activity_at", type: "TIMESTAMP WITH TIME ZONE", isNullable: true, description: "Timestamp of most recent transaction" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Wallet registration timestamp" },
      { name: "updated_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Balance sync timestamp" },
    ],
    indexes: ["idx_wallets_address", "idx_wallets_member_id", "idx_wallets_account_id", "idx_wallets_balance_btc", "idx_wallets_is_flagged"],
  },

  transactions: {
    name: "transactions",
    category: "Ledger & Blockchain",
    description: "Bitcoin on-chain transactions, synthetic demo records (100 txs), fees, block heights, and risk flags",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "tx_id", type: "VARCHAR(128)", isUnique: true, description: "Synthetic transaction ID (DEMO-TX-001-BITFLOW)" },
      { name: "tx_hash", type: "VARCHAR(128)", isUnique: true, isNullable: true, description: "64-character hex on-chain transaction hash" },
      { name: "member_id", type: "UUID", isNullable: true, references: { table: "members", column: "id", onDelete: "SET NULL" }, description: "Associated member ID" },
      { name: "wallet_id", type: "UUID", isNullable: true, references: { table: "wallets", column: "id", onDelete: "SET NULL" }, description: "Associated wallet ID" },
      { name: "sender_name", type: "VARCHAR(255)", description: "Synthetic sender individual name" },
      { name: "sender_address", type: "VARCHAR(128)", description: "Bitcoin sender address" },
      { name: "receiver_address", type: "VARCHAR(128)", description: "Bitcoin recipient address" },
      { name: "receiver_name", type: "VARCHAR(255)", description: "Synthetic receiver individual name" },
      { name: "amount_btc", type: "NUMERIC(18, 8)", description: "Transfer amount in BTC" },
      { name: "amount_usd", type: "NUMERIC(18, 2)", description: "USD fiat equivalent valuation" },
      { name: "network_fee_btc", type: "NUMERIC(18, 8)", defaultValue: "0.00001000", description: "Miner network fee in BTC" },
      { name: "fee_rate_sat_vb", type: "NUMERIC(10, 2)", defaultValue: "15.00", description: "Miner fee rate in satoshis per vByte" },
      { name: "vsize", type: "INTEGER", defaultValue: "225", description: "Virtual size in vBytes" },
      { name: "confirmations", type: "INTEGER", defaultValue: "0", description: "Blockchain confirmation depth" },
      { name: "block_height", type: "INTEGER", isNullable: true, description: "Block height number" },
      { name: "payment_phase", type: "VARCHAR(50)", defaultValue: "'Payment'", description: "Pre-Payment | Payment | Post-Payment" },
      { name: "payment_status", type: "VARCHAR(50)", defaultValue: "'Success'", description: "Success | Pending | Failed" },
      { name: "direction", type: "VARCHAR(50)", defaultValue: "'Outgoing'", description: "Incoming | Outgoing | Internal" },
      { name: "tx_type", type: "VARCHAR(50)", defaultValue: "'Wallet transfer'", description: "Wallet transfer | Exchange transfer | P2P" },
      { name: "mempool_status", type: "VARCHAR(50)", defaultValue: "'Confirmed'", description: "Confirmed | In Mempool | Accelerated" },
      { name: "is_whale", type: "BOOLEAN", defaultValue: "FALSE", description: "Flagged if amount >= whale threshold (e.g. 5 BTC)" },
      { name: "whale_tier", type: "VARCHAR(50)", defaultValue: "'Small/Regular'", description: "Small/Regular | Tier-1 Whale | Mega Whale" },
      { name: "risk_flag", type: "VARCHAR(50)", defaultValue: "'Normal'", description: "Normal | Review | High Risk | Critical" },
      { name: "risk_score", type: "INTEGER", defaultValue: "10", description: "Risk score index 0-100" },
      { name: "ai_interpretation", type: "TEXT", isNullable: true, description: "Heuristic and anomaly explanation" },
      { name: "ai_decision_note", type: "TEXT", isNullable: true, description: "SOC decision rationale" },
      { name: "raw_tx_data", type: "JSONB", defaultValue: "'{}'::jsonb", description: "Raw transaction telemetry" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Transaction timestamp" },
      { name: "confirmed_at", type: "TIMESTAMP WITH TIME ZONE", isNullable: true, description: "Block confirmation timestamp" },
      { name: "updated_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Last state transition timestamp" },
    ],
    indexes: ["idx_transactions_tx_id", "idx_transactions_member_id", "idx_transactions_wallet_id", "idx_transactions_sender_address", "idx_transactions_receiver_address", "idx_transactions_risk_score", "idx_transactions_risk_flag", "idx_transactions_is_whale", "idx_transactions_created_at"],
  },

  risk_assessments: {
    name: "risk_assessments",
    category: "Detection & Intelligence",
    description: "Explainable multi-factor scoring (Velocity, Fan-In/Out, Peeling Chains, ML Anomaly)",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "transaction_id", type: "UUID", references: { table: "transactions", column: "id", onDelete: "CASCADE" }, description: "Assessed transaction reference" },
      { name: "wallet_address", type: "VARCHAR(128)", description: "Target wallet evaluated" },
      { name: "composite_score", type: "INTEGER", description: "Weighted aggregate risk score (0-100)" },
      { name: "risk_tier", type: "VARCHAR(50)", description: "LOW | MEDIUM | HIGH | CRITICAL" },
      { name: "velocity_score", type: "INTEGER", defaultValue: "0", description: "Velocity burst score component" },
      { name: "amount_anomaly_score", type: "INTEGER", defaultValue: "0", description: "Z-score amount anomaly factor" },
      { name: "fan_in_out_score", type: "INTEGER", defaultValue: "0", description: "Convergence / dispersion rating" },
      { name: "peeling_chain_score", type: "INTEGER", defaultValue: "0", description: "Peeling chain layering metric" },
      { name: "counterparty_risk_score", type: "INTEGER", defaultValue: "0", description: "Counterparty exposure rating" },
      { name: "heuristic_flags", type: "JSONB", defaultValue: "'[]'::jsonb", description: "Triggered rule identifiers" },
      { name: "ml_isolation_score", type: "NUMERIC(6, 4)", defaultValue: "0.0000", description: "Isolation Forest anomaly index" },
      { name: "confidence_pct", type: "INTEGER", defaultValue: "95", description: "Evaluation statistical confidence %" },
      { name: "summary", type: "TEXT", description: "High level analyst summary" },
      { name: "decision_reasoning", type: "TEXT", description: "Comprehensive mathematical rationale" },
      { name: "assessed_by", type: "VARCHAR(100)", defaultValue: "'BitFlow-AI-HeuristicEngine-v3'", description: "Evaluating engine model tag" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Assessment generated timestamp" },
    ],
    indexes: ["idx_risk_assessments_tx_id", "idx_risk_assessments_wallet_address", "idx_risk_assessments_risk_tier", "idx_risk_assessments_composite_score"],
  },

  wallet_features: {
    name: "wallet_features",
    category: "Detection & Intelligence",
    description: "Rolling statistical features, velocity z-scores, holding duration, and counterparty entropy",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "wallet_address", type: "VARCHAR(128)", isUnique: true, description: "Bitcoin address monitored" },
      { name: "inflow_btc_24h", type: "NUMERIC(18, 8)", defaultValue: "0.00000000", description: "24-hour total incoming BTC" },
      { name: "outflow_btc_24h", type: "NUMERIC(18, 8)", defaultValue: "0.00000000", description: "24-hour total outgoing BTC" },
      { name: "tx_count_24h", type: "INTEGER", defaultValue: "0", description: "24-hour transaction frequency" },
      { name: "inflow_btc_7d", type: "NUMERIC(18, 8)", defaultValue: "0.00000000", description: "7-day total incoming BTC" },
      { name: "outflow_btc_7d", type: "NUMERIC(18, 8)", defaultValue: "0.00000000", description: "7-day total outgoing BTC" },
      { name: "tx_count_7d", type: "INTEGER", defaultValue: "0", description: "7-day transaction frequency" },
      { name: "avg_holding_duration_sec", type: "INTEGER", defaultValue: "86400", description: "Mean holding duration before transfer" },
      { name: "unique_counterparties_count", type: "INTEGER", defaultValue: "1", description: "Count of distinct address counterparties" },
      { name: "velocity_zscore", type: "NUMERIC(8, 4)", defaultValue: "0.0000", description: "Statistical standard deviations from baseline" },
      { name: "amount_zscore", type: "NUMERIC(8, 4)", defaultValue: "0.0000", description: "Amount deviation standard score" },
      { name: "fan_in_ratio", type: "NUMERIC(6, 4)", defaultValue: "0.0000", description: "Convergence ratio" },
      { name: "fan_out_ratio", type: "NUMERIC(6, 4)", defaultValue: "0.0000", description: "Dispersion ratio" },
      { name: "rapid_forwarding_rate", type: "NUMERIC(6, 4)", defaultValue: "0.0000", description: "Forwarded vs received amount ratio" },
      { name: "cluster_affinity_score", type: "INTEGER", defaultValue: "0", description: "Syndicate cluster affinity rating" },
      { name: "risk_level", type: "VARCHAR(50)", defaultValue: "'LOW'", description: "Current dynamic risk tier" },
      { name: "last_calculated_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Feature calculation timestamp" },
    ],
    indexes: ["idx_wallet_features_address", "idx_wallet_features_velocity_zscore", "idx_wallet_features_risk_level"],
  },

  network_edges: {
    name: "network_edges",
    category: "Detection & Intelligence",
    description: "Directed on-chain graph edges with hop indices and pattern tags (Multi-hop, Rapid-forward)",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "transaction_id", type: "UUID", isNullable: true, references: { table: "transactions", column: "id", onDelete: "CASCADE" }, description: "Originating transaction reference" },
      { name: "source_wallet", type: "VARCHAR(128)", description: "Source bitcoin address" },
      { name: "target_wallet", type: "VARCHAR(128)", description: "Destination bitcoin address" },
      { name: "source_member_id", type: "VARCHAR(32)", isNullable: true, description: "Sender synthetic member ID" },
      { name: "target_member_id", type: "VARCHAR(32)", isNullable: true, description: "Receiver synthetic member ID" },
      { name: "amount_btc", type: "NUMERIC(18, 8)", description: "Edge transfer volume in BTC" },
      { name: "amount_usd", type: "NUMERIC(18, 2)", description: "Edge valuation in USD" },
      { name: "hop_order", type: "INTEGER", defaultValue: "1", description: "Hop position in multi-hop chain (1, 2, 3, 4)" },
      { name: "flow_type", type: "VARCHAR(50)", defaultValue: "'DIRECT'", description: "DIRECT | PEELING_CHAIN | RAPID_FORWARD | FAN_IN | FAN_OUT" },
      { name: "is_cycle", type: "BOOLEAN", defaultValue: "FALSE", description: "Circular flow cycle flag" },
      { name: "latency_seconds", type: "INTEGER", isNullable: true, description: "Transit latency from predecessor hop" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Edge detection timestamp" },
    ],
    indexes: ["idx_network_edges_source", "idx_network_edges_target", "idx_network_edges_tx_id", "idx_network_edges_flow_type"],
  },

  network_clusters: {
    name: "network_clusters",
    category: "Detection & Intelligence",
    description: "Co-spending heuristics and suspicious syndicates identified by network graph algorithms",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "cluster_name", type: "VARCHAR(100)", isUnique: true, description: "Unique syndicate or cluster designation" },
      { name: "cluster_type", type: "VARCHAR(50)", description: "MULTI_HOP_SYNDICATE | RAPID_DISPERSAL | CIRCULAR_WASH" },
      { name: "root_wallet", type: "VARCHAR(128)", description: "Seed or originator wallet address" },
      { name: "wallet_count", type: "INTEGER", defaultValue: "1", description: "Total entities clustered" },
      { name: "transaction_count", type: "INTEGER", defaultValue: "1", description: "Aggregated transactions in cluster" },
      { name: "total_volume_btc", type: "NUMERIC(18, 8)", defaultValue: "0.00000000", description: "Aggregated cluster volume in BTC" },
      { name: "risk_level", type: "VARCHAR(50)", defaultValue: "'HIGH'", description: "Syndicate threat level: MEDIUM | HIGH | CRITICAL" },
      { name: "associated_member_ids", type: "JSONB", defaultValue: "'[]'::jsonb", description: "Array of affected member IDs" },
      { name: "heuristic_signature", type: "VARCHAR(128)", description: "Mathematical topology signature hash" },
      { name: "detected_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "First detection timestamp" },
      { name: "updated_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Last expansion timestamp" },
    ],
    indexes: ["idx_network_clusters_type", "idx_network_clusters_risk", "idx_network_clusters_root"],
  },

  alerts: {
    name: "alerts",
    category: "SOC Operations",
    description: "Deduplicated threat alerts, state transitions (NEW, ACKNOWLEDGED, RESOLVED), and rule triggers",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "alert_code", type: "VARCHAR(32)", isUnique: true, description: "Human readable alert ID (ALT-9001)" },
      { name: "title", type: "VARCHAR(255)", description: "Descriptive alert title" },
      { name: "alert_type", type: "VARCHAR(50)", description: "NETWORK_CONVERGENCE | RAPID_FORWARDING | FAN_IN | FAN_OUT | CIRCULAR_FLOW" },
      { name: "severity", type: "VARCHAR(50)", defaultValue: "'HIGH'", description: "LOW | MEDIUM | HIGH | CRITICAL" },
      { name: "risk_score", type: "INTEGER", description: "Alert risk score index (0-100)" },
      { name: "status", type: "VARCHAR(50)", defaultValue: "'NEW'", description: "NEW | ACKNOWLEDGED | INVESTIGATING | RESOLVED | FALSE_POSITIVE" },
      { name: "wallet_address", type: "VARCHAR(128)", description: "Target wallet under alert" },
      { name: "transaction_id", type: "UUID", isNullable: true, references: { table: "transactions", column: "id", onDelete: "SET NULL" }, description: "Associated transaction ID" },
      { name: "flow_summary", type: "TEXT", isNullable: true, description: "Path summary (e.g. X -> A -> B -> C -> F)" },
      { name: "reasons", type: "JSONB", defaultValue: "'[]'::jsonb", description: "Array of heuristic violation strings" },
      { name: "dedup_count", type: "INTEGER", defaultValue: "1", description: "Event deduplication counter" },
      { name: "acknowledged_by", type: "UUID", isNullable: true, references: { table: "users", column: "id", onDelete: "SET NULL" }, description: "Analyst who claimed alert" },
      { name: "acknowledged_at", type: "TIMESTAMP WITH TIME ZONE", isNullable: true, description: "Acknowledgment timestamp" },
      { name: "resolved_by", type: "UUID", isNullable: true, references: { table: "users", column: "id", onDelete: "SET NULL" }, description: "Analyst who closed alert" },
      { name: "resolved_at", type: "TIMESTAMP WITH TIME ZONE", isNullable: true, description: "Resolution timestamp" },
      { name: "resolution_note", type: "TEXT", isNullable: true, description: "Final disposition note" },
      { name: "last_event_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Latest matching event timestamp" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Initial trigger timestamp" },
      { name: "updated_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Last state change timestamp" },
    ],
    indexes: ["idx_alerts_alert_code", "idx_alerts_severity", "idx_alerts_status", "idx_alerts_wallet", "idx_alerts_risk_score", "idx_alerts_created_at"],
  },

  investigations: {
    name: "investigations",
    category: "SOC Operations",
    description: "Formal investigation dossiers, evidence attachments, hypothesis, and case closure notes",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "case_number", type: "VARCHAR(32)", isUnique: true, description: "Official case code (INV-2026-001)" },
      { name: "title", type: "VARCHAR(255)", description: "Case headline and hypothesis" },
      { name: "target_wallet", type: "VARCHAR(128)", description: "Primary entity of interest wallet" },
      { name: "target_member_id", type: "VARCHAR(32)", isNullable: true, description: "Primary synthetic member ID" },
      { name: "target_tx_id", type: "VARCHAR(128)", isNullable: true, description: "Trigger transaction identifier" },
      { name: "status", type: "VARCHAR(50)", defaultValue: "'OPEN'", description: "OPEN | IN_PROGRESS | CLOSED" },
      { name: "priority", type: "VARCHAR(50)", defaultValue: "'HIGH'", description: "LOW | MEDIUM | HIGH | CRITICAL" },
      { name: "lead_analyst", type: "VARCHAR(255)", description: "Assigned lead investigator" },
      { name: "lead_analyst_id", type: "UUID", isNullable: true, references: { table: "users", column: "id", onDelete: "SET NULL" }, description: "Analyst user reference" },
      { name: "risk_score", type: "INTEGER", defaultValue: "50", description: "Assessed syndicate threat score" },
      { name: "detected_patterns", type: "JSONB", defaultValue: "'[]'::jsonb", description: "Array of detected crime patterns" },
      { name: "findings", type: "TEXT", description: "Investigative observations and findings" },
      { name: "conclusion", type: "TEXT", isNullable: true, description: "Regulatory conclusion and filing advice" },
      { name: "evidence_payload", type: "JSONB", defaultValue: "'{}'::jsonb", description: "Attached ledger evidence and snapshots" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Case opening timestamp" },
      { name: "updated_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Last dossier update timestamp" },
      { name: "closed_at", type: "TIMESTAMP WITH TIME ZONE", isNullable: true, description: "Final closure timestamp" },
    ],
    indexes: ["idx_investigations_case_number", "idx_investigations_status", "idx_investigations_target_wallet", "idx_investigations_risk_score"],
  },

  investigation_events: {
    name: "investigation_events",
    category: "SOC Operations",
    description: "Chronological audit timeline events tied to investigation dossiers",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "investigation_id", type: "UUID", references: { table: "investigations", column: "id", onDelete: "CASCADE" }, description: "Parent case dossier reference" },
      { name: "event_type", type: "VARCHAR(50)", defaultValue: "'NOTE'", description: "ALERT_LINKED | NOTE | WALLET_TAGGED | EVIDENCE_ADDED | STATUS_CHANGE" },
      { name: "description", type: "TEXT", description: "Event narrative description" },
      { name: "severity", type: "VARCHAR(50)", defaultValue: "'info'", description: "info | warning | critical" },
      { name: "analyst_name", type: "VARCHAR(255)", description: "Author of timeline entry" },
      { name: "analyst_id", type: "UUID", isNullable: true, references: { table: "users", column: "id", onDelete: "SET NULL" }, description: "Analyst user reference" },
      { name: "evidence_reference", type: "VARCHAR(255)", isNullable: true, description: "External document or transaction pointer" },
      { name: "event_payload", type: "JSONB", defaultValue: "'{}'::jsonb", description: "Event metadata parameters" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Event occurrence timestamp" },
    ],
    indexes: ["idx_investigation_events_inv_id", "idx_investigation_events_created_at"],
  },

  audit_logs: {
    name: "audit_logs",
    category: "Audit & System",
    description: "Immutable SOC security access log, analyst decisions, and administrative actions",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "user_id", type: "UUID", isNullable: true, references: { table: "users", column: "id", onDelete: "SET NULL" }, description: "User ID performing action" },
      { name: "username", type: "VARCHAR(100)", description: "User handle" },
      { name: "action", type: "VARCHAR(100)", description: "Action key (e.g. LOGIN, ACKNOWLEDGE_ALERT, EXPORT_REPORT)" },
      { name: "resource", type: "VARCHAR(100)", description: "Resource type (e.g. ALERT, CASE, TRANSACTION)" },
      { name: "resource_id", type: "VARCHAR(128)", isNullable: true, description: "Specific resource identifier" },
      { name: "details", type: "TEXT", isNullable: true, description: "Audit trail descriptive detail" },
      { name: "ip_address", type: "VARCHAR(45)", defaultValue: "'127.0.0.1'", description: "Origin client IP address" },
      { name: "user_agent", type: "VARCHAR(255)", isNullable: true, description: "Browser or API client string" },
      { name: "created_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Audit timestamp" },
    ],
    indexes: ["idx_audit_logs_user_id", "idx_audit_logs_username", "idx_audit_logs_action", "idx_audit_logs_resource", "idx_audit_logs_created_at"],
  },

  data_imports: {
    name: "data_imports",
    category: "Audit & System",
    description: "Ingestion tracking for Excel workbooks (Transactions and Members KYC demo sheets)",
    primaryKey: "id",
    columns: [
      { name: "id", type: "UUID", isPrimary: true, description: "Primary database UUID" },
      { name: "import_code", type: "VARCHAR(32)", isUnique: true, description: "Unique batch code (IMP-INIT-001)" },
      { name: "filename", type: "VARCHAR(255)", description: "Original spreadsheet or file name" },
      { name: "file_type", type: "VARCHAR(50)", defaultValue: "'XLSX'", description: "XLSX | CSV | JSON" },
      { name: "records_found", type: "INTEGER", defaultValue: "0", description: "Parsed rows in source file" },
      { name: "records_imported", type: "INTEGER", defaultValue: "0", description: "Successfully inserted records" },
      { name: "duplicates_count", type: "INTEGER", defaultValue: "0", description: "Deduplicated rows" },
      { name: "invalid_count", type: "INTEGER", defaultValue: "0", description: "Malformed or invalid records" },
      { name: "status", type: "VARCHAR(100)", defaultValue: "'SUCCESS'", description: "Ingestion execution status" },
      { name: "file_size_bytes", type: "BIGINT", isNullable: true, description: "File size in bytes" },
      { name: "checksum_sha256", type: "VARCHAR(64)", isNullable: true, description: "SHA-256 integrity hash" },
      { name: "imported_by", type: "VARCHAR(100)", defaultValue: "'System Ingestion Worker'", description: "Import executor" },
      { name: "imported_at", type: "TIMESTAMP WITH TIME ZONE", defaultValue: "CURRENT_TIMESTAMP", description: "Ingestion timestamp" },
    ],
    indexes: ["idx_data_imports_code", "idx_data_imports_status", "idx_data_imports_imported_at"],
  },
};
